var app = require('koa')();
var mongoose = require('mongoose');
var router = require('koa-router')();
var parser = require('koa-bodyparser');
var passport = require('koa-passport');
require('./config/passport')(passport); 
app.use(passport.initialize());
mongoose.connect('mongodb://localhost/facebook');
var usersController = require('./user-controller');
app.use(parser());
app.use(router.routes());
usersController(router,passport);
app.listen(8000);
